import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  heading: {
    fontSize: 22,
    fontWeight: '600',
    color: '#000',
    paddingTop: 2,
    flex: 1,
    alignSelf: 'center',
  },
  note: {
    fontSize: 18,
    fontWeight: '600',
    width: '100%',
    alignSelf: 'center',
    marginTop: 10,
  },
  modalLine: {
    height: 1,
    backgroundColor: '#e0e0e0',
    width: '100%',
    marginVertical: 10,
    marginTop: 20,
  },
  priority: {
    fontSize: 20,
    fontWeight: '600',
    //paddingLeft: 8,
    //paddingTop: 5,
    paddingBottom: 8,
    width: '100%',
    alignSelf: 'center',
    textAlign: 'center',
    //right: -230,
  },
  dltibtn: {
    width: 22,
    height: 22,
    //right: -310,
    marginTop: 5,
    marginRight: 20,
  },
  editbtn: {
    width: 20,
    height: 20,
    //right: -255,
    marginTop: 7,
    marginRight: 10,
  },
  container: {
    //justifyContent: 'space-between',
    width: '100%',
    alignSelf: 'center',
    backgroundColor: '#fff',
    marginTop: 10,
    borderRadius: 10,
    elevation: 4,
    padding: 12,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.8,
    shadowRadius: 10,
  },
});

export default styles;
